version: "3.8"

services:
  consensus-app:
    user: node
    build: ./app/
    volumes:
      - ./app:/app
      - /app/node_modules/
    ports:
      - 4000:4000
    container_name: consensus-app

  consensus-api:
    user: node
    build: ./api/
    volumes:
      - ./api:/api
      - /api/node_modules/
    ports:
      - 3000:3000
    container_name: consensus-api
    
    